spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456
      # >= 8.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定 nacos server 的地址
        server-addr: localhost:8848
  application:
    # 服务名称尽量使用 -，不要用 _，不要用特殊字符
    name: content-center

server:
  port: 8010