spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=Hongkong
    hikari:
      username: root
      password: 123456
      # >= 8.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是 0.1 (10%)
      probability: 1.0
  cloud:
    nacos:
      discovery:
        # 指定 nacos server 的地址
        server-addr: localhost:8848
        # 指定 namespace
        # namespace: 777cec93-3f26-45f3-91cd-fe61bb5352a6
        cluster-name: BJ
        # 设置元数据
        metadata:
          # 自己这个版本的实例
          version: v1
          # 允许调用的提供者版本
          target-version: v1
    sentinel:
      filter:
        # 打开/关闭掉对 SpringMVC 端点的保护
        enabled: true
      transport:
        # 指定 sentinel 控制台的地址
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          # 用来指定 topic
          destination: add-bonus



  main:
    allow-bean-definition-overriding: true

server:
  port: 8010

# 配置属性方式
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 日志
logging:
  level:
    com.itchen.contentcenter.feignclient.UserCenterFeignClient: debug
    com.alibaba.nacos: error
    com.itchen.contentcenter.dao.share: debug

# Feign 配置属性方式(全局/细粒度)
feign:
  sentinel:
    # 为 feign 整合 sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.itchen.contentcenter.feignclient.Interceptor.TokenRelayRequestInterceptor
        # 想要调用的微服务的名称(细粒度)
        # user-center:
        # loggerLevel: full
  httpclient:
    # 让 feign 使用 Apache HTTPclient 做请求；而不是默认的 URLconnection
    enabled: true
    # feign 的最大连接数
    max-connections: 200
    # feign 单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resttemplate:
  sentinel:
    # 关闭 @SentinelRestTemplate 注解
    enabled: false

jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认 2 周
  expire-time-in-second: 1209600

your:
  configuration: